version: "3"
services:
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - 8888:8888
    volumes:
      - /Users/sami/caset/psychic-invention/:/home/jovyan/work
volumes:
  my_volume:
    external: true